"""Delivery and manifest helpers."""

from __future__ import annotations

from datetime import UTC, datetime, timedelta
from pathlib import Path

from scripts.notify.state import load_json, parse_issue_key
from scripts.shared.converters import to_int, to_string_list


def prune_delivery_dedupe(
    delivery_dedupe: dict[str, str],
    retention_days: int,
) -> dict[str, str]:
    """
    Prune old dedupe records.

    Args:
        delivery_dedupe: Dedupe map.
        retention_days: Retention day count.

    Returns:
        Pruned map.
    """
    if retention_days <= 0:
        return {}

    cutoff = datetime.now(UTC) - timedelta(days=retention_days)
    kept: dict[str, str] = {}
    for key, value in delivery_dedupe.items():
        try:
            parsed = datetime.fromisoformat(value)
        except ValueError:
            continue
        if parsed.tzinfo is None:
            parsed = parsed.replace(tzinfo=UTC)
        if parsed >= cutoff:
            kept[key] = value
    return kept


def resolve_path(path_value: str, project_root: Path) -> Path:
    """
    Resolve path relative to project root.

    Args:
        path_value: Raw path argument.
        project_root: Project root path.

    Returns:
        Resolved path.
    """
    path = Path(path_value)
    if path.is_absolute():
        return path
    return project_root / path


def load_change_manifest(
    path: Path,
    db_name: str,
) -> tuple[list[str], list[str], list[int], str | None]:
    """
    Load a change manifest generated by the index update task.

    Args:
        path: Change manifest path.
        db_name: Active database file name.

    Returns:
        Pending issue keys, pending in-press journal ids,
        pending article ids, and run id.
    """
    payload = load_json(path, None)
    if not isinstance(payload, dict):
        raise ValueError(f"Invalid change manifest file: {path}")

    manifest_db = str(payload.get("db_name") or "").strip()
    if manifest_db and manifest_db != db_name:
        raise ValueError(
            f"Change manifest database mismatch: expected {db_name}, got {manifest_db}"
        )

    raw_issue_keys = to_string_list(payload.get("changed_issue_keys"))
    pending_issue_keys = sorted(
        {
            issue_key
            for issue_key in raw_issue_keys
            if ":" in issue_key and len(issue_key.split(":", maxsplit=1)) == 2
        },
        key=lambda item: parse_issue_key(item),
    )

    pending_inpress_keys: list[str] = []
    seen_inpress_keys: set[str] = set()
    raw_inpress_values = payload.get("changed_inpress_journal_ids")
    if isinstance(raw_inpress_values, list):
        for value in raw_inpress_values:
            journal_id = to_int(value)
            if journal_id is None:
                continue
            journal_key = str(journal_id)
            if journal_key in seen_inpress_keys:
                continue
            seen_inpress_keys.add(journal_key)
            pending_inpress_keys.append(journal_key)
    pending_inpress_keys.sort(key=lambda item: int(item))

    pending_article_ids: list[int] = []
    seen_article_ids: set[int] = set()
    raw_article_values = payload.get("notifiable_article_ids")
    if not isinstance(raw_article_values, list):
        raise ValueError("Change manifest missing notifiable_article_ids")
    for value in raw_article_values:
        article_id = to_int(value)
        if article_id is None:
            continue
        if article_id in seen_article_ids:
            continue
        seen_article_ids.add(article_id)
        pending_article_ids.append(article_id)

    run_id_value = str(payload.get("run_id") or "").strip()
    run_id = run_id_value or None
    return pending_issue_keys, pending_inpress_keys, pending_article_ids, run_id
